### ISSUE TITLE
Unable to create single organization network 

### ISSUE THREAD

**Issue by jorgedr94** [IBM-Blockchain/ansible-collection#151]
**Summary:**
Tried to create single organization network using a Software installation of IBP.   The playbook used is based on the one-org-network sample but it only creates one peer.   Peer, CAs and Orderer are created but playbook fails on `Retrieve current system channel configuration block` step. Details below.  

**Error message:**
```
TASK [ibm.blockchain_platform_manager : Delete all organisations] ********************************************************************
skipping: [localhost] => (item={'msp': {'id': 'Org1MSP', 'admin': {'identity': 'org1Admin', 'secret': 'org1Adminpw'}, 'ibp': {'display_name': 'Org1 MSP'}}, 'ca': {'id': 'Org1CA', 'admin_identity': 'admin', 'admin_secret': 'adminpw', 'tls': {'enabled': True}, 'docker': {'name': 'ca.org1.example.com', 'hostname': 'ca.org1.example.com', 'port': 18050}, 'ibp': {'display_name': 'Org1 CA'}}, 'peers': [{'id': 'Org1Peer1', 'identity': 'org1peer1', 'secret': 'org1peer1pw', 'database_type': 'leveldb', 'tls': {'enabled': True, 'identity': 'org1peer1tls', 'secret': 'org1peer1tlspw'}, 'docker': {'name': 'peer0.org1.example.com', 'hostname': 'peer0.org1.example.com', 'port': 18051, 'chaincode_port': 18052, 'operations_port': 18053, 'couchdb': {'name': 'couchdb0.org1.example.com', 'hostname': 'couchdb0.org1.example.com', 'port': 18054}}, 'ibp': {'display_name': 'Org1 Peer1'}}], 'nodes': '/Users/jorgedr/Documents/demos/IBP-Advanced-Demos/ansible-examples/one-org-network/nodes/Org1', 'wallet': '/Users/jorgedr/Documents/demos/IBP-Advanced-Demos/ansible-examples/one-org-network/wallets/Org1', 'gateways': '/Users/jorgedr/Documents/demos/IBP-Advanced-Demos/ansible-examples/one-org-network/gateways/Org1'}) 
skipping: [localhost] => (item={'msp': {'id': 'OrdererMSP', 'admin': {'identity': 'ordererAdmin', 'secret': 'ordererAdminpw'}, 'ibp': {'display_name': 'Orderer MSP'}}, 'ca': {'id': 'OrdererCA', 'admin_identity': 'admin', 'admin_secret': 'adminpw', 'tls': {'enabled': True}, 'docker': {'name': 'ca.orderer.example.com', 'hostname': 'ca.orderer.example.com', 'port': 17050}, 'ibp': {'display_name': 'Orderer CA'}}, 'orderer': {'id': 'Orderer1', 'identity': 'orderer1', 'secret': 'orderer1pw', 'tls': {'enabled': True, 'identity': 'orderer1tls', 'secret': 'orderer1tlspw'}, 'consortium': {'members': [{'msp': {'id': 'Org1MSP', 'admin': {'identity': 'org1Admin', 'secret': 'org1Adminpw'}, 'ibp': {'display_name': 'Org1 MSP'}}, 'ca': {'id': 'Org1CA', 'admin_identity': 'admin', 'admin_secret': 'adminpw', 'tls': {'enabled': True}, 'docker': {'name': 'ca.org1.example.com', 'hostname': 'ca.org1.example.com', 'port': 18050}, 'ibp': {'display_name': 'Org1 CA'}}, 'peers': [{'id': 'Org1Peer1', 'identity': 'org1peer1', 'secret': 'org1peer1pw', 'database_type': 'leveldb', 'tls': {'enabled': True, 'identity': 'org1peer1tls', 'secret': 'org1peer1tlspw'}, 'docker': {'name': 'peer0.org1.example.com', 'hostname': 'peer0.org1.example.com', 'port': 18051, 'chaincode_port': 18052, 'operations_port': 18053, 'couchdb': {'name': 'couchdb0.org1.example.com', 'hostname': 'couchdb0.org1.example.com', 'port': 18054}}, 'ibp': {'display_name': 'Org1 Peer1'}}], 'nodes': '/Users/jorgedr/Documents/demos/IBP-Advanced-Demos/ansible-examples/one-org-network/nodes/Org1', 'wallet': '/Users/jorgedr/Documents/demos/IBP-Advanced-Demos/ansible-examples/one-org-network/wallets/Org1', 'gateways': '/Users/jorgedr/Documents/demos/IBP-Advanced-Demos/ansible-examples/one-org-network/gateways/Org1'}]}, 'docker': {'name': 'orderer.example.com', 'hostname': 'orderer.example.com', 'port': 17051, 'operations_port': 17052}, 'ibp': {'display_name': 'Orderer1', 'cluster_name': 'OrdererCluster'}}, 'nodes': '/Users/jorgedr/Documents/demos/IBP-Advanced-Demos/ansible-examples/one-org-network/nodes/Orderer', 'wallet': '/Users/jorgedr/Documents/demos/IBP-Advanced-Demos/ansible-examples/one-org-network/wallets/Orderer', 'gateways': '/Users/jorgedr/Documents/demos/IBP-Advanced-Demos/ansible-examples/one-org-network/gateways/Orderer'}) 

TASK [ibm.blockchain_platform_manager : Manage all consortiums] **********************************************************************
skipping: [localhost] => (item={'msp': {'id': 'Org1MSP', 'admin': {'identity': 'org1Admin', 'secret': 'org1Adminpw'}, 'ibp': {'display_name': 'Org1 MSP'}}, 'ca': {'id': 'Org1CA', 'admin_identity': 'admin', 'admin_secret': 'adminpw', 'tls': {'enabled': True}, 'docker': {'name': 'ca.org1.example.com', 'hostname': 'ca.org1.example.com', 'port': 18050}, 'ibp': {'display_name': 'Org1 CA'}}, 'peers': [{'id': 'Org1Peer1', 'identity': 'org1peer1', 'secret': 'org1peer1pw', 'database_type': 'leveldb', 'tls': {'enabled': True, 'identity': 'org1peer1tls', 'secret': 'org1peer1tlspw'}, 'docker': {'name': 'peer0.org1.example.com', 'hostname': 'peer0.org1.example.com', 'port': 18051, 'chaincode_port': 18052, 'operations_port': 18053, 'couchdb': {'name': 'couchdb0.org1.example.com', 'hostname': 'couchdb0.org1.example.com', 'port': 18054}}, 'ibp': {'display_name': 'Org1 Peer1'}}], 'nodes': '/Users/jorgedr/Documents/demos/IBP-Advanced-Demos/ansible-examples/one-org-network/nodes/Org1', 'wallet': '/Users/jorgedr/Documents/demos/IBP-Advanced-Demos/ansible-examples/one-org-network/wallets/Org1', 'gateways': '/Users/jorgedr/Documents/demos/IBP-Advanced-Demos/ansible-examples/one-org-network/gateways/Org1'}) 
included: /Users/jorgedr/.ansible/roles/ibm.blockchain_platform_manager/tasks/manage-consortium.yml for localhost

TASK [ibm.blockchain_platform_manager : Retrieve current system channel configuration block] *****************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["peer", "channel", "fetch", "config", "/var/folders/2q/0w_rkb1d32z_hz0qwdrdtk1c0000gn/T/ansible.69t8zq19/config_block.pb", "-o", "my-ibp-orderer1node1-orderer.console-openshift-console.apps.ibpupdatedemo.os.fyre.ibm.com:443", "-c", "testchainid", "--tls", "--cafile", "/Users/jorgedr/Documents/demos/IBP-Advanced-Demos/ansible-examples/one-org-network/wallets/Orderer/tls-root.pem"], "delta": "0:00:00.468694", "end": "2020-04-15 16:39:08.850083", "msg": "non-zero return code", "rc": 1, "start": "2020-04-15 16:39:08.381389", "stderr": "Error: failed to create deliver client: orderer client failed to connect to my-ibp-orderer1node1-orderer.console-openshift-console.apps.ibpupdatedemo.os.fyre.ibm.com:443: failed to create new connection: connection error: desc = \"transport: error while dialing: dial tcp: lookup my-ibp-orderer1node1-orderer.console-openshift-console.apps.ibpupdatedemo.os.fyre.ibm.com on 192.168.1.1:53: no such host\"", "stderr_lines": ["Error: failed to create deliver client: orderer client failed to connect to my-ibp-orderer1node1-orderer.console-openshift-console.apps.ibpupdatedemo.os.fyre.ibm.com:443: failed to create new connection: connection error: desc = \"transport: error while dialing: dial tcp: lookup my-ibp-orderer1node1-orderer.console-openshift-console.apps.ibpupdatedemo.os.fyre.ibm.com on 192.168.1.1:53: no such host\""], "stdout": "", "stdout_lines": []}

PLAY RECAP ***************************************************************************************************************************
localhost                  : ok=143  changed=40   unreachable=0    failed=1    skipped=3    rescued=0    ignored=0   
```

**Playbook used is as follows:**

```
#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Deploy blockchain infrastructure and smart contracts
  hosts: localhost
  vars:
    #
    # For information on these configuration options, read the documentation:
    # https://github.com/IBM-Blockchain/ansible-role-blockchain-platform-manager#example-playbook
    #
    infrastructure:
      type: software
      docker:
        network: ibp_network
      saas: "{{ lookup('file', 'service-creds.json') | from_json }}"
      software:
        api_endpoint: <xxx>
        api_key: <xxx>
        api_secret: <xxx>
    organizations:
      - &Org1
        msp:
          id: "Org1MSP"
          admin:
            identity: "org1Admin"
            secret: "org1Adminpw"
          ibp:
            display_name: "Org1 MSP"
        ca: &Org1CA
          id: "Org1CA"
          admin_identity: "admin"
          admin_secret: "adminpw"
          tls:
            enabled: true
          docker:
            name: ca.org1.example.com
            hostname: ca.org1.example.com
            port: 18050
          ibp:
            display_name: "Org1 CA"
        peers:
          - &Org1Peer1
            id: "Org1Peer1"
            identity: "org1peer1"
            secret: "org1peer1pw"
            database_type: leveldb
            tls:
              enabled: true
              identity: "org1peer1tls"
              secret: "org1peer1tlspw"
            docker:
              name: peer0.org1.example.com
              hostname: peer0.org1.example.com
              port: 18051
              chaincode_port: 18052
              operations_port: 18053
              couchdb:
                name: couchdb0.org1.example.com
                hostname: couchdb0.org1.example.com
                port: 18054
            ibp:
              display_name: "Org1 Peer1"
        nodes: "{{ playbook_dir }}/nodes/Org1"
        wallet: "{{ playbook_dir }}/wallets/Org1"
        gateways: "{{ playbook_dir }}/gateways/Org1"
      - &OrdererOrg
        msp:
          id: "OrdererMSP"
          admin:
            identity: "ordererAdmin"
            secret: "ordererAdminpw"
          ibp:
            display_name: "Orderer MSP"
        ca: &OrdererCA
          id: "OrdererCA"
          admin_identity: "admin"
          admin_secret: "adminpw"
          tls:
            enabled: true
          docker:
            name: ca.orderer.example.com
            hostname: ca.orderer.example.com
            port: 17050
          ibp:
            display_name: "Orderer CA"
        orderer: &Orderer
          id: "Orderer1"
          identity: "orderer1"
          secret: "orderer1pw"
          tls:
            enabled: true
            identity: "orderer1tls"
            secret: "orderer1tlspw"
          consortium:
            members:
              - *Org1
          docker:
            name: orderer.example.com
            hostname: orderer.example.com
            port: 17051
            operations_port: 17052
          ibp:
            display_name: "Orderer1"
            cluster_name: "OrdererCluster"
        nodes: "{{ playbook_dir }}/nodes/Orderer"
        wallet: "{{ playbook_dir }}/wallets/Orderer"
        gateways: "{{ playbook_dir }}/gateways/Orderer"
    channels:
      - &Channel1
        name: channel1
        orderer: *Orderer
        members:
          - <<: *Org1
            committing_peers:
              - *Org1Peer1
            anchor_peers:
              - *Org1Peer1
    contracts:
      - name: fabcar
        version: 1.0.0
        package: "{{ playbook_dir }}/fabcar@1.0.0.cds"
        channels:
          - <<: *Channel1
            endorsement_policy: "AND('Org1MSP.member')"
            endorsing_members:
              - <<: *Org1
                endorsing_peers:
                  - <<: *Org1Peer1
    gateways:
      - name: Org1 gateway
        organization:
          <<: *Org1
          gateway_peers:
            - <<: *Org1Peer1
  roles:
    - ibm.blockchain_platform_manager

```
