### ISSUE TITLE
Unable to pass in organization as structure rather than name for channel creation

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/ansible-collection#155]
You should be able to pass in an organization as either a name, or a dictionary (object) with all the required properties:

```
    - name: Create the configuration update for the new channel
      ibm.blockchain_platform.channel_config:
        api_endpoint: "{{ api_endpoint }}"
        api_authtype: "{{ api_authtype }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret | default(omit) }}"
        api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
        operation: create
        name: mychannel
        path: config_update.bin
        organizations:
          - "{{ lookup('file', 'Org2.json' )}}"
        policies:
          Admins: 08-admins-policy.json
          Readers: 08-readers-policy.json
          Writers: 08-writers-policy.json
```

However, this doesn't work - the passed dictionary (object) should be turned into an instance of `Organization` first, but isn't.
