### ISSUE TITLE
Timing window on console install where deployment doesn't exist yet

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/ansible-collection#190]
Reported by MGK - we wait for the console deployment to become ready:

```
- name: Wait for console deployment to start
  k8s:
    state: present
    namespace: "{{ project }}"
    api_version: apps/v1
    kind: Deployment
    name: "{{ console }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"
  changed_when: False
```

However, there is a small window where the operator hasn't yet created the console deployment, and this task fails as it tries to create an empty deployment with the same name. Unfortunately the `k8s_info` module doesn't let you wait, only the `k8s` module does.

We need to loop and wait for the deployment to exist before waiting for it to become ready.
