### ISSUE TITLE
IBP console: support multizone & storage config

### ISSUE THREAD

**Issue by alxiong** [IBM-Blockchain/ansible-collection#249]
Currently IBP installation playbook doesn't support [multizone openshift cluster](https://cloud.ibm.com/docs/blockchain-sw-213?topic=blockchain-sw-213-deploy-ocp#console-deploy-ocp-advanced) & `storage` config yet.

```yaml
storage:
  console:
    class: <non-default-storageclass>
    size: 50Gi
clusterdata:
  zones:
    - dal10
    - dal12
    - dal13
```

Final config could look like:
```yaml
---
- name: Deploy IBM Blockchain Platform console
  hosts: localhost
  vars:
    state: present
    target: openshift
    arch: amd64
    project: <project>
    image_registry_password: <image_registry_password>
    image_registry_email: <image_registry_email>
    console_domain: <console_domain>
    console_email: <console_email>
    console_default_password: <console_default_password>
    wait_timeout: 3600
    storage:
      console:
        class: my-storage-class
        size: 50Gi 
    clusterdata:
      zones:
        - dal10
        - dal12
        - dal13
  roles:
    - ibm.blockchain_platform.console
```
