### ISSUE TITLE
Removal of peer/ordering service requires too many parameters

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/ansible-collection#335]
```
- name: Delete peer
  ibm.blockchain_platform.peer:
    state: "{{ state }}"
    api_endpoint: "{{ api_endpoint }}"
    api_authtype: "{{ api_authtype }}"
    api_key: "{{ api_key }}"
    api_secret: "{{ api_secret | default(omit) }}"
    api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
    name: "{{ peer_name }}"
    # HACK: this shouldn't be required
    config: {}
```

We shouldn't need the `config` parameter when the `state` is set to `absent` - we only do because of the Ansible argument validation. It doesn't allow us to say "require config or certificate authority IF state is present" so we will have to handle this ourselves.
