### ISSUE TITLE
Adding additional peers and orderers

### ISSUE THREAD

**Issue by aakzubaidi** [IBM-Blockchain/ansible-collection#521]
Hi,
I am using the tutorial playbooks and editing them to bring up 3 orderers and 2 peers for org1
One peer should be endorsing and the other is only committing. 

I referred to the manual and module references and even some of the source code, trying to reason what I should consider for adding multiple peers and what parameters I should add or edit.

More specifically:
- I added an additional peer_name in file org1Vars.yml. I then created an additional task in the second yml file (endorsing organisation.. yml. However, I couldn't reason how to properly join it in the channel in file10 and how to include it the genesis block. 
- for orderers, I specified the number in files orderersVars.yml. I do not see them in the main page of the IBM Blockchain console. However, I can see them when I click on the orderer organisation. Is this normal?

The following shows how I tried to add orderers in file **ordering-org-vars.yml**:
`ordering_service_nodes: 3`

and this is how I added a task to add another peer  in the following files:
in file **org1-vars.yml**
```yaml
ca_admin_enrollment_id: admin
ca_admin_enrollment_secret: adminpw
organization_admin_enrollment_id: org1admin
organization_admin_enrollment_secret: org1adminpw
peer_enrollment_id: org1peer
peer_enrollment_secret: org1peerpw
application_enrollment_id: org1app
application_enrollment_secret: org1apppw
application_enrollment_type: client
application_max_enrollments: 10
org1_ca_name: "Org1 CA"
##edited the files to declare peers names. I did not specify the number of the peers
org1_peer1_name: "Org1 Peer1"
org1_peer2_name: "Org1 Peer2"
wait_timeout: 600
```

in file **02-create-endorsing-organization-components.yml**:
``` yaml
- name: Create org1peer1
  hosts: localhost
  vars:
    state: present
    organization_name: "{{ org1_name }}"
    organization_msp_id: "{{ org1_msp_id }}"
    ca_name: "{{ org1_ca_name }}"
    peer_name: "{{ org1_peer1_name }}"
  vars_files:
    - common-vars.yml
    - org1-vars.yml
  roles:
    - ibm.blockchain_platform.endorsing_organization

##added task for the additional peer
- name: Create org1peer2
  hosts: localhost
  vars:
    state: present
    organization_name: "{{ org1_name }}"
    organization_msp_id: "{{ org1_msp_id }}"
    ca_name: "{{ org1_ca_name }}"
    peer_name: "{{ org1_peer2_name }}"
  vars_files:
    - common-vars.yml
    - org1-vars.yml
  roles:
    - ibm.blockchain_platform.endorsing_organization
```

in file **10-join-peer-to-channel.yml**

```yaml
    - name: Join the peer to the channel
      ibm.blockchain_platform.peer_channel:
        api_endpoint: "{{ api_endpoint }}"
        api_authtype: "{{ api_authtype }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret | default(omit) }}"
        api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
        operation: join
       ## I am not sure about the following line
        peer: "{{ org1_peer1_name }, { org1_peer2_name }}"
        identity: "{{ org1_name }} Admin.json"
        msp_id: "{{ org1_msp_id }}"
        path: channel_genesis_block.bin

```

Eventually, I see the peers and ordered in the blockchain console, however, I get the error 

![image](https://user-images.githubusercontent.com/8116425/107635385-f5b7f280-6c62-11eb-9d9d-ead0d7f4f705.png)
