### ISSUE TITLE
Support Fabric CA 1.5.5: idemix curve

### ISSUE THREAD

**Issue by arner** [IBM-Blockchain/ansible-collection#635]
The Ansible Scripts support creating 1.5.5 Fabric CA's, but there is a new config parameter that does not get used by the Operator (the curve), and it causes the whole idemix block to be ignored. I tried in the certificate_authority task with:
```

config_override:
          ca:
            idemix:
              rhpoolsize: 1000
              nonceexpiration: 15s
              noncesweepinterval: 15m
              curve: gurvy.Bn254
```
No errors on creation.

But in the UI, the Idemix paragraph doesn't show up in the JSON config for the CA.

Also an update in the UI with
```
"ca": {
    "idemix": {
    "rhpoolsize": 1000,
    "nonceexpiration": "15s",
    "noncesweepinterval": "15m",
    "curve": "gurvy.Bn254"
  }
}
```
Does not stick.

When I inspect the config.yaml in the pod, there is no Idemix paragraph.

I followed https://hyperledger-fabric-ca.readthedocs.io/en/release-1.4/serverconfig.html
for the format and values (plus the curve). When I only had the curve specified, I got an error so there is a component that checks the format and it seems I have it in the right place.
